<table style="width:100%;">
    <tr>
        <th valign="top" style="width:100%;background-color:#336699;padding:2.25pt;border-style:none;">
            <span style="color:#ffffff;"><?php echo Mage::helper("dog")->__("Abandoned Carts Report"); ?></span>
         </th>
    </tr>
    <tr>
        <td>
            <table style="width:100%;">
                <?php
                $_info = array(
                    array(
                        "label" => Mage::helper("dog")->__("Total Abandoned Carts Today (%s)", $this->getToday()),
                        "value" => '<b>' . $this->getTotalCount() . '</b>'
                    ),
                    array(
                        "label" => Mage::helper("dog")->__("Total Abandoned Value (%s)", $this->getToday()),
                        "value" => '<b>' . $this->getTotalValue() . '</b>'
                    ),                                  
                );
                foreach($_info as $_row)
                {
                    echo '<tr><td style="font-size:9pt; height:15pt;padding:2.25pt; text-align:right;"><span style="color:#3366CC;"> ' . $_row["label"] . '</span></td>';
                    echo '<td style="width:60">&nbsp;</td><td style="font-size:9pt; text-align:center;"><span style="color:#3366CC;">' . $_row["value"] . '</span></td></tr>';
                }
                ?>
            </table>            
        </td>
    </tr>
    <tr>
        <td>
            <table style="width:100%;">
                <tr>
                    <th style="font-size:9pt;text-align:center;"><b>Customer</b></th>
                    <th style="font-size:9pt;text-align:center;"><b>Time last Updated</b></th>
                    <th style="font-size:9pt;text-align:center;"><b>Abandoned Value</b></th>
                </tr>
                <?php
                $_i = 0;
                foreach($this->getData("items") as $_row)
                {
                    $_product = Mage::getModel("catalog/product")->load($_row->getData("product_id"));
                    echo '<tr>';
                    $_keys = array(
                        'fullname',
                        'updated_at',
                        'base_grand_total',
                    );
                    foreach($_keys as $_k)
                    {
                        switch($_k)
                        {
                            case "base_grand_total":
                                $_value = $this->_moneyFormat($_row->getData($_k));
                                break;
                            default:
                                $_value = $_row->getData($_k);
                                break; 
                        }
                        echo '<td style="text-align:center;';
                        if ($_i % 2 == 0) echo ' background-color:#E5E6E9;';
                        echo '"><span style="color:#3366CC; font-size:9pt;text-align:center;">' . $_value . '</span></td>';
                    }
                    $_i++;
                    echo '</tr>';
                   }
                ?>
            </table>
        </td>
    </tr>
        
</table>