<div style="background:#F6F6F6; font-family:Verdana, Arial, Helvetica, sans-serif; font-size:12px; margin:0;">
<table cellspacing="0" cellpadding="0" border="0" width="100%">
<tr>
    <td align="center" valign="top" style="padding:20px 0 20px 0">
        <table bgcolor="#FFFFFF" cellspacing="0" cellpadding="10" border="0" width="700" style="border:1px solid #E0E0E0; padding:12px; font-size: 12px;">
            <!-- [ header starts here] -->
            <tr>
                <td width="214" valign="top" style="text-align:left;">
                <span style="color:#3366cc; font-size:9pt; line-height:16pt"><img src="http://www.CustomerParadigm.com/images/Magento/Watchdog/Magento-Watchdog-75.gif" alt="Magento Watchdog" width="75" height="74" hspace="10" vspace="0" align="left"></span><span style="color:#3366cc; font-size:9pt; line-height:16pt"><span style="font-size:13pt; font-weight:bold;">Watchdog is keeping <br>
                an eye on your store.
                <br>
                </span></span><span style="color:#3366cc; font-size:9pt; line-height:16pt"><br/>
                </span></td>
                <td width="394" valign="top" style="width:200px; text-align:right;">
                        <a href="http://www.customerparadigm.com" style="text-decoration:none;">
                                <span style="color:#3366CC; font-size:6pt;">Powered By</span><br/>
                                <img src="http://www.CustomerParadigm.com/images/Magento/Watchdog/Customer-Paradigm-Magento-Partner-logo-160.jpg" alt="Customer Paradigm - Magento Experts" width="160" height="50" border="0"><br/>
                                <span style="color:#3366CC; font-size:8pt;"><b>Need Help? Click here >></b><br/> 
                                or call 303.473.4400</span>
                        </a>
                        </td>
            </tr>
            <!-- [ middle starts here] -->
            <tr>
                <td style="text-align:left; width:100%;" colspan="2">
                  <p style="color:#3366cc; font-size:9pt; line-height:16pt"><span style="font-size:13pt; font-weight:bold;">What Is Watchdog?<br>
                  </span>Watchdog is a Magento plugin that sends email alerts, including a daily sales summary email, or email alerts based on triggers (a spike in sales, low sales, or error messages in Magento, php or on your site).</p>
                  <hr width="85%">
                  <br>
                  <p style="color:#3366cc; font-size:9pt; line-height:16pt"><span style="font-size:13pt; font-weight:bold;">How Much Does Watchdog Cost?<br>
                  </span>Watchdog is a free Magento plugin. As such, you agree to hold Customer Paradigm harmless for any issues from delayed email alerts or system errors that could occur.</p>
                  <hr width="85%">
                  <p style="color:#3366cc; font-size:9pt; line-height:16pt">&nbsp;</p>
                  <p style="color:#3366cc; font-size:9pt; line-height:16pt"><span style="font-size:13pt; font-weight:bold;">How Does Watchdog Work?<br>
                  </span>Once Watchdog is installed (see details below), you can set up daily sales summary emails (and tell the system when to send them, and for what store), as well as triggers that will send you and your specified contacts email alerts if there is a spike in sales.</p>
                  <hr width="85%">
                  <p style="color:#3366cc; font-size:9pt; line-height:16pt">&nbsp;</p>
                  <p style="color:#3366cc; font-size:9pt; line-height:16pt"><span style="font-size:13pt; font-weight:bold;">Why Watchdog?<br>
                  </span>Customer Paradigm created the Watchdog system, based on requests from our clients.</p>
                  <p style="color:#3366cc; font-size:9pt; line-height:16pt">The two biggest complaints from our clients about Magento:</p>
                  <p style="color:#3366cc; font-size:9pt; line-height:16pt"><em><strong>1. &quot;I wish I could automatically receive a summary at the end of the day with the total sales for the day.&quot;</strong></em><br>
                    <br>
Magento store owners know they can always log into the admin, but email is a push mechanism, and allows someone to receive a summary of the daily sales quickly and easily. It's perfect for the store owner, or upper management, who wants reports, but needs them sent in an easy manner.</p>
                  <p style="color:#3366cc; font-size:9pt; line-height:16pt"><em><strong>2. &quot;I wish there was an automatic way the site can alert me if things go really well or really wrong.&quot;</strong></em></p>
                  <p style="color:#3366cc; font-size:9pt; line-height:16pt">Instead of relying on &quot;I think the site is working,&quot; or &quot;I'm not sure if there's been a big spike in sales,&quot; automatic triggers create alert emails that tell you if:</p>
                  <p style="color:#3366cc; font-size:9pt; line-height:16pt">* You've had more than 50 orders in the last half hour (a spike in sales)<br>
                  * You haven't had any orders in the last 12 hours (might mean something is wrong with the site).<br>
                  * 
                  There are errors on the site.</p>
                  <p style="color:#3366cc; font-size:9pt; line-height:16pt">Customer Paradigm developed Watchdog as a way to have an automated system watch over your store, and inform you via email.</p>
                  <hr width="85%">
                  <p style="color:#3366cc; font-size:9pt; line-height:16pt">&nbsp;</p>
                  <p style="color:#3366cc; font-size:9pt; line-height:16pt"><span style="font-size:13pt; font-weight:bold;">How to Use  Watchdog:<br>
                  </span>Watchdog is easy to use, and starts with setting up the settings tab:</p>
                  <hr width="85%">
              <p style="color:#3366cc; font-size:9pt; line-height:16pt">&nbsp;</p></td>
          </tr>
            <tr>
                <td valign="top" colspan="2"><p style="color:#3366cc; font-size:9pt; line-height:16pt"><span style="font-size:13pt; font-weight:bold;">Watchdog - Settings:<br>
                </span></p>
                  <p style="color:#3366cc; font-size:9pt; line-height:16pt"><a href="http://www.customerparadigm.com/images/Magento/Watchdog/Magento-Watchdog-Settings-Screenshot.gif" target="_blank"><img src="http://www.customerparadigm.com/images/Magento/Watchdog/Magento-Watchdog-Master-Settings-Screenshot-450.gif" alt="Watchdog - Settings" width="450" height="424" border="0"></a></p>
                  <p style="color:#3366cc; font-size:9pt; line-height:16pt"><a href="http://www.customerparadigm.com/images/Magento/Watchdog/Magento-Watchdog-Settings-Screenshot.gif" target="_blank">View larger screenshot &gt;&gt;</a></p>
                  <p style="color:#3366cc; font-size:9pt; line-height:16pt">After you agree to the terms and conditions for the Watchdog system, you need to set up the following information:</p>
                  <p style="color:#3366cc; font-size:9pt; line-height:16pt"><strong>Master Email Addresses:</strong><br>
                    Master email addresses will receive ALL alerts sent out of the system.  
                  Type in email addresses, separated by a comma.<br>
                  <strong><br>
                  Email Sender:</strong><br>
                  This is the friendly display name and email address for email alerts sent from the Watchdog system.  For best results, the sender email address should be an email address associated with the domain name of the main Magento store.  If you try using a Yahoo, Gmail or other email address, spam filters may prevent your Watchdog emails from being delivered properly.<br>
                  <br>
                  <strong>Stores:<br>
                  </strong>Choose which stores you'd like Watchdog to monitor. For many Magento sites, there is only a single store.<br>
                  <strong><br>
                  External Account ID: </strong><br>
                  In the event that your server is non-resonsive or crashes, the Watchdog system will not be able to send alert emails.  In this case, our external Watchdog server will send an External Watchdog Alert to the Master Email Addresses, informing you that there is an issue with your site.</p>
                  <p style="color:#3366cc; font-size:9pt; line-height:16pt">&nbsp;</p>
                  <p style="color:#3366cc; font-size:9pt; line-height:16pt"><strong>Save Button: <br>
                  </strong>Make sure to hit the <img src="http://www.customerparadigm.com/images/Magento/Watchdog/save-button.gif" alt="Save" width="104" height="43" align="absmiddle">button so your settings are saved.  If you edit your Master Email Addresses, they will be updated as well on the external Watchdog server, hosted by Customer Paradigm.<br>
                    <br>
                  </p>
                  <hr width="85%">
                <p style="color:#3366cc; font-size:9pt; line-height:16pt"></p></td>
            </tr>
            <tr>
              <td colspan="2" valign="top"><p style="color:#3366cc; font-size:9pt; line-height:16pt"><span style="font-size:13pt; font-weight:bold;">Watchdog - Daily Sales Summary Email:<br>
              </span></p>
                <p style="color:#3366cc; font-size:9pt; line-height:16pt"><a href="http://www.customerparadigm.com/images/Magento/Watchdog/Magento-Watchdog-Create-View-Daily-Summary-Email.gif" target="_blank"><img src="http://www.customerparadigm.com/images/Magento/Watchdog/Magento-Watchdog-Create-View-Daily-Summary-Email-450.gif" alt="Daily Summary Emails" width="450" height="161" border="0"></a></p>
                <p style="color:#3366cc; font-size:9pt; line-height:16pt"><a href="http://www.customerparadigm.com/images/Magento/Watchdog/Magento-Watchdog-Create-View-Daily-Summary-Email.gif" target="_blank">View larger screenshot &gt;&gt;</a></p>
                <p style="color:#3366cc; font-size:9pt; line-height:16pt"><strong>To set up a Daily Sales Summary Email, Navigate to the main Daily Sales Summary Email Page.</strong></p>
                <p style="color:#3366cc; font-size:9pt; line-height:16pt"><strong>You can have separate Daily Sales Summary emails for each store, or create one roll-up report that aggregates sales information across all stores. </strong></p>
                <p style="color:#3366cc; font-size:9pt; line-height:16pt"><strong>You can also set the time when the Daily Sales Summary email will be triggered (i.e. 10 am, 1 pm or 11:55 pm). The system will only pull data from midnight of the current day.</strong></p>
                <p style="color:#3366cc; font-size:9pt; line-height:16pt"><strong>You can:</strong></p>
                <p style="color:#3366cc; font-size:9pt; line-height:16pt">1. View Existing Daily Sales Summary emails, and edit / delete when they are sent, what stores are included, and who receives summary emails.</p>
                <p style="color:#3366cc; font-size:9pt; line-height:16pt"><a href="http://www.customerparadigm.com/images/Magento/Watchdog/Magento-Watchdog-View-Existing-Daily-Summary-Alerts.gif" target="_blank"><img src="http://www.customerparadigm.com/images/Magento/Watchdog/Magento-Watchdog-View-Existing-Daily-Summary-Alerts-450.gif" alt="View Existing Daily Sales Summary" width="450" height="123" border="0"><br>
                View larger screenshot &gt;&gt;</a></p>
                <p style="color:#3366cc; font-size:9pt; line-height:16pt"><strong>To edit an exisiting Daily Sales Summary, simply click on the row.</strong></p>
                <hr width="85%">
                <p style="color:#3366cc; font-size:9pt; line-height:16pt"><strong>2. Or, Create a New Daily Summary Email, by clicking the Add New Button:</strong></p>
                <p style="color:#3366cc; font-size:9pt; line-height:16pt"><img src="http://www.customerparadigm.com/images/Magento/Watchdog/add-new-button.gif" width="104" height="43" alt="Add New"></p>                
                <p><span style="color:#3366cc; font-size:9pt; line-height:16pt"><br/>
                  <br/>
              </span><a href="http://www.customerparadigm.com/images/Magento/Watchdog/Magento-Watchdog-Create-New-Daily-Summary-Email-General-Tab.gif" target="_blank"><img src="http://www.customerparadigm.com/images/Magento/Watchdog/Magento-Watchdog-Create-New-Daily-Summary-Email-General-Tab-450.gif" alt="Daily Sales Summary - Add New" width="450" height="291" border="0"></a></p>
                <p style="color:#3366cc; font-size:9pt; line-height:16pt"><a href="http://www.customerparadigm.com/images/Magento/Watchdog/Magento-Watchdog-Create-New-Daily-Summary-Email-General-Tab.gif" target="_blank">View larger screenshot &gt;&gt;</a></p>
                <p style="color:#3366cc; font-size:9pt; line-height:16pt"><strong>Summary Email Name:<br>
                </strong>This is the name of your daily sales summary email report.  This will appear in the subject line of your email alerts.<br>
                <br>
                <strong>Select Time:</strong><br>
                Select the time you would like to receive the alert.
                <br>
                <strong>Note: </strong>Send time is based on the timezone of your server, and the report will be from 12 am the current day until the selected time. The system will display your current server time.<br>
                If you have multiple summary reports, the sales information will always be from 12:00 am the current day until the selected time (i.e. it will not start from the time of the previous report).
                </p>
                <p style="color:#3366cc; font-size:9pt; line-height:16pt"><strong>Select Store(s):</strong><br>
                  Select the store or stores from which you would like to receive a daily summary report. <br>
                If you select multiple stores, the report will aggregate (combine) all of the sales into one roll up report.</p>
                <p style="color:#3366cc; font-size:9pt; line-height:16pt">If you would like to have individual reports for each store, please create a report for each store separately. </p>
                <p style="color:#3366cc; font-size:9pt; line-height:16pt"><strong>Save Button: <br>
                </strong>Make sure to hit the <img src="http://www.customerparadigm.com/images/Magento/Watchdog/save-button.gif" alt="Save" width="104" height="43" align="absmiddle">button so your settings are saved.</p>
                <hr width="85%">
                <p style="color:#3366cc; font-size:9pt; line-height:16pt">&nbsp;</p>
                <p style="color:#3366cc; font-size:9pt; line-height:16pt"><span style="font-size:13pt; font-weight:bold;">Summary Reports Tab:<br>
                </span></p>
                <p style="color:#3366cc; font-size:9pt; line-height:16pt"><br>
                  <a href="http://www.customerparadigm.com/images/Magento/Watchdog/Magento-Watchdog-Create-New-Daily-Summary-Sales-Email-Summary-Report-Options.gif" target="_blank"><img src="http://www.customerparadigm.com/images/Magento/Watchdog/Magento-Watchdog-Create-New-Daily-Summary-Sales-Email-Summary-Report-Options-450.gif" alt="Summary Reports Tab Options" width="450" height="389" border="0"></a><br>
                <a href="http://www.customerparadigm.com/images/Magento/Watchdog/Magento-Watchdog-Create-New-Daily-Summary-Sales-Email-Summary-Report-Options.gif" target="_blank">View larger screenshot &gt;&gt;</a></p>
                <p style="color:#3366cc; font-size:9pt; line-height:16pt">On the Summary Reports tab, you can select which reports you'd like to have included in the Daily Sales Summary Report. By default, everything is checked:                </p>
                <p><br>
[x] Sales Totals<br>
The Sales Totals report will give you information regarding the monetary performance of your store(s).                </p>
                <p>Avg Order Size for the given day<br>
                  Total Ordered Today<br>
                  Total Invoiced Today<br>
                  Total Refunded Today<br>
                Additional Information:</p>
                <p>WTD (Week-to-date) Sales<br>
                  MTD (Month-to-date) Sales<br>
                  YTD (Year-to-date) Sales<br>
                  Lifetime Sales<br>
                  </p>
                <p>[x] Sales Orders<br>
                  The Sales Orders report will give you header-level information about every order that was placed on your store</p>
                <p>A report in the format: Order # | Date | Customer Name | Amount | Order Status<br>
                  <br>
                  [x] Bestsellers<br>
                The Bestsellersms report will give you detailed information about the items sold on your store each day</p>
<p>A report in the format: Item # (Sku) | Qty Ordered | Product Price | Total Value | Avg Unit Price<br>
                *Above report will be sorted by best-worst sellers (Max of 25 products)<br>
                </p>
<p>[x] Abandoned Carts<br>
                The Abandoned Carts report lets you know how many customers did not complete their orders, and shows you the potential revenue in their carts.</p>
<p>Total # of Abandoned Carts<br>
                Total $$ of Abandoned Carts<br>
                A report in the format: Customer Name / Customer Email | Time last Updated | Abandoned Value<br>
                <br>
                [x] 
                Coupons Used<br>
                The Coupons Used report is vital for any marketing team. It gives you detailed information about coupon usage on your site</p>
<p>Total # of Coupons Used<br>
                Total $$ discounted by Coupons<br>
                A report in the format: Coupon Code | Coupon Name | Coupon Type | # Uses | Total Discount Amount<br>
                </p>
<p>[x] Customers<br>
                The Customers report gives you detailed information about customer acquisition and retainment</p>
<p>Total # of New Customers<br>
                Total # of Customers<br>
                Information Regarding Active Customers:</p>
                <p># Active Today<br>
                  # Active this week<br>
                  # Active this month<br>
                # Active this year                </p>
                <p><br>
                  <br>
                  <span style="color:#3366cc; font-size:9pt; line-height:16pt"><strong>Save Button: <br>
                </strong>Make sure to hit the <img src="http://www.customerparadigm.com/images/Magento/Watchdog/save-button.gif" alt="Save" width="104" height="43" align="absmiddle">button so your settings are saved.</span>                </p>
                <hr width="85%">
                <p>&nbsp;</p></td>
            </tr>
            <tr>
              <td colspan="2" valign="top"><p style="color:#3366cc; font-size:9pt; line-height:16pt"><span style="font-size:13pt; font-weight:bold;">Watchdog Daily Sales Summary Contacts Tab:<br>
                <br>
              </span><a href="http://www.customerparadigm.com/images/Magento/Watchdog/Magento-Watchdog-Create-New-Daily-Summary-Email-Email-Contacts-Page.gif" target="_blank"><img src="http://www.customerparadigm.com/images/Magento/Watchdog/Magento-Watchdog-Create-New-Daily-Summary-Email-Email-Contacts-Page-450.gif" alt="Magento Daily Summary Contacts Tab" width="450" height="268" border="0"></a></p>
<p style="color:#3366cc; font-size:9pt; line-height:16pt"><a href="http://www.customerparadigm.com/images/Magento/Watchdog/Magento-Watchdog-Create-New-Daily-Summary-Email-Email-Contacts-Page.gif" target="_blank">View larger screenshot &gt;&gt;</a>                </p>
              <p style="color:#3366cc; font-size:9pt; line-height:16pt"><strong>On the Watchdog Daily Sales Summary Contacts Tab, you can add additional contacts who want to receive the Daily Sales Summary Email.</strong></p>
              <p style="color:#3366cc; font-size:9pt; line-height:16pt"><strong>By default, ALL Master Contacts will receive every report.</strong></p>
              <p style="color:#3366cc; font-size:9pt; line-height:16pt">To change the Master Contacts, navigate to:<br>
                <em>CustomerParadigm-&gt;Watchdog-&gt;Settings</em></p>
              <p style="color:#3366cc; font-size:9pt; line-height:16pt"><strong>Email Contacts:</strong></p>
              <p style="color:#3366cc; font-size:9pt; line-height:16pt">By default all reports are emailed to the Master Contacts, listed above.</p>
              <p style="color:#3366cc; font-size:9pt; line-height:16pt"> If you would like to have this specific report sent to an additional person, please select from the email contacts below.<br>
                <br>
                To add a new email contact, please visit<br>
                <em>CustomerParadigm-&gt;Watchdog-&gt;Contacts</em></p>
              <p style="color:#3366cc; font-size:9pt; line-height:16pt"><br>
                <strong>Save Button: <br>
              </strong>Make sure to hit the <img src="http://www.customerparadigm.com/images/Magento/Watchdog/save-button.gif" alt="Save" width="104" height="43" align="absmiddle">button so your settings are saved.</p>
              <hr width="85%">
              <p style="color:#3366cc; font-size:9pt; line-height:16pt">&nbsp;</p></td>
          </tr>
            <tr>
              <td colspan="2" valign="top"><p style="color:#3366cc; font-size:9pt; line-height:16pt"><span style="font-size:13pt; font-weight:bold;">Watchdog - Contacts:</span></p>
                <p style="color:#3366cc; font-size:9pt; line-height:16pt"><span style="font-size:13pt; font-weight:bold;"><br>
                </span><a href="http://www.customerparadigm.com/images/Magento/Watchdog/Magento-Watchdog-Contacts-System.gif" target="_blank"><img src="http://www.customerparadigm.com/images/Magento/Watchdog/Magento-Watchdog-Contacts-System-450.gif" alt="Watchdog Contacts" width="450" height="128" border="0"></a><br>
                <a href="http://www.customerparadigm.com/images/Magento/Watchdog/Magento-Watchdog-Contacts-System.gif" target="_blank">View larger screenshot &gt;&gt;</a>                </p>
              <p style="color:#3366cc; font-size:9pt; line-height:16pt">In the Watchdog system, you can add additional contacts who wish to receive specific alert emails.</p>
              <p style="color:#3366cc; font-size:9pt; line-height:16pt">For example, a manager of the store may only wish to see a single roll-up report at the end of the day, but a person who works on the site all of the time may instead wish to have reports sent several times per day.</p>
              <p style="color:#3366cc; font-size:9pt; line-height:16pt">By default, all alerts are sent to the Master Email Address list. You can use the contact system to add, remove or edit existing contacts for Daily Sales Summary Alerts and Trigger Alerts.</p>
              <hr width="85%">
              <p style="color:#3366cc; font-size:9pt; line-height:16pt"><br>
              </p></td>
            </tr>
            <tr>
              <td colspan="2" valign="top"><p style="color:#3366cc; font-size:9pt; line-height:16pt"><span style="font-size:13pt; font-weight:bold;">Watchdog - Triggers:</span></p>
                <p style="color:#3366cc; font-size:9pt; line-height:16pt"><span style="font-size:13pt; font-weight:bold;"><a href="http://www.customerparadigm.com/images/Magento/Watchdog/Magento-Watchdog-Triggers-First-Screen.gif" target="_blank"><img src="http://www.customerparadigm.com/images/Magento/Watchdog/Magento-Watchdog-Triggers-First-Screen-450.gif" alt="Trigger Alerts" width="450" height="142" border="0"></a><br>
                  </span><br>
                  <a href="http://www.customerparadigm.com/images/Magento/Watchdog/Magento-Watchdog-Triggers-First-Screen.gif" target="_blank">View larger screenshot &gt;&gt;</a></p>
              <p style="color:#3366cc; font-size:9pt; line-height:16pt"><strong>You can view existing triggers (to edit or remove them), or create a new trigger easily.</strong></p>
              <hr width="85%">
              <p style="color:#3366cc; font-size:9pt; line-height:16pt">&nbsp;</p></td>
            </tr>
            <tr>
              <td colspan="2" valign="top"><p style="color:#3366cc; font-size:9pt; line-height:16pt"><span style="font-size:13pt; font-weight:bold;">Watchdog - View Existing Triggers:</span></p>
                <p style="color:#3366cc; font-size:9pt; line-height:16pt"><span style="font-size:13pt; font-weight:bold;"><a href="http://www.customerparadigm.com/images/Magento/Watchdog/Magento-Watchdog-View-Edit-Trigger-Alert-Emails.gif" target="_blank"><img src="http://www.customerparadigm.com/images/Magento/Watchdog/Magento-Watchdog-View-Edit-Trigger-Alert-Emails-450.gif" alt="View Existing Triggers" width="450" height="165" border="0"></a><br>
                  </span><br>
                <a href="http://www.customerparadigm.com/images/Magento/Watchdog/Magento-Watchdog-View-Edit-Trigger-Alert-Emails.gif" target="_blank">View larger screenshot &gt;&gt;</a></p>
              <p style="color:#3366cc; font-size:9pt; line-height:16pt"><strong>From this screen, you are able to view existing triggers (to edit or remove them), or create a new trigger easily by clicking on &quot;Add New.&quot; To edit an existing trigger, click on the row.</strong></p>
              <hr width="85%">
              <p style="color:#3366cc; font-size:9pt; line-height:16pt">&nbsp;</p></td>
            </tr>
            <tr>
              <td colspan="2" valign="top"><p style="color:#3366cc; font-size:9pt; line-height:16pt"><span style="font-size:13pt; font-weight:bold;">Watchdog - Add New Triggers (General Tab):</span></p>
                <p style="color:#3366cc; font-size:9pt; line-height:16pt"><span style="font-size:13pt; font-weight:bold;"><a href="http://www.customerparadigm.com/images/Magento/Watchdog/Magento-Watchdog-Create-New-Trigger-General-Tab.gif" target="_blank"><img src="http://www.customerparadigm.com/images/Magento/Watchdog/Magento-Watchdog-Create-New-Trigger-General-Tab-450.gif" alt="Add New Trigger - General Tab" width="450" height="189" border="0"></a><br>
                  </span><br>
                <a href="http://www.customerparadigm.com/images/Magento/Watchdog/Magento-Watchdog-Create-New-Trigger-General-Tab.gif" target="_blank">View larger screenshot &gt;&gt;</a></p>
              <p style="color:#3366cc; font-size:9pt; line-height:16pt"><strong>From this screen, you are can name the Trigger, and associate it with one or more stores.</strong></p>
              <p style="color:#3366cc; font-size:9pt; line-height:16pt"><strong>Trigger Name: </strong><br>
                The trigger name is displayed in the email alert, and should be descriptive. </p>
              <p style="color:#3366cc; font-size:9pt; line-height:16pt">For example, you might want to name a trigger, &quot;Big Order Spike Alert- 50 in Half Hour.&quot; Or, &quot;Less than 5 sales in a day.&quot;              </p>
              <p style="color:#3366cc; font-size:9pt; line-height:16pt"><strong>Store: </strong><br>
                Select the store or stores you would like the trigger to use for generating an alert email.</p>
              <p style="color:#3366cc; font-size:9pt; line-height:16pt"><strong>Save Button: <br>
              </strong>Make sure to hit the <img src="http://www.customerparadigm.com/images/Magento/Watchdog/save-button.gif" alt="Save" width="104" height="43" align="absmiddle">button so your settings are saved.</p>
              <hr width="85%">
              <p style="color:#3366cc; font-size:9pt; line-height:16pt">&nbsp;</p></td>
            </tr>
            <tr>
              <td colspan="2" valign="top"><p style="color:#3366cc; font-size:9pt; line-height:16pt"><span style="font-size:13pt; font-weight:bold;">Watchdog - Add New Triggers (Conditions Tab):</span></p>
                <p style="color:#3366cc; font-size:9pt; line-height:16pt"><span style="font-size:13pt; font-weight:bold;"><a href="http://www.customerparadigm.com/images/Magento/Watchdog/Magento-Watchdog-Create-New-Trigger-Trigger-Type-Selection-Screen.gif" target="_blank"><img src="http://www.customerparadigm.com/images/Magento/Watchdog/Magento-Watchdog-Create-New-Trigger-Trigger-Type-Selection-Screen-450.gif" alt="Watchdog - Select Type of Trigger" width="450" height="302" border="0"></a><br>
                  </span><br>
                <a href="http://www.customerparadigm.com/images/Magento/Watchdog/Magento-Watchdog-Create-New-Trigger-Trigger-Type-Selection-Screen.gif" target="_blank">View larger screenshot &gt;&gt;</a></p>
                <hr width="85%">
                <p style="color:#3366cc; font-size:9pt; line-height:16pt"><strong>From this screen, you are can</strong> <strong>select one of two types of Triggers (more to be added soon):</strong></p>
              <p style="color:#3366cc; font-size:9pt; line-height:16pt"><strong><strong><img src="http://www.customerparadigm.com/images/Magento/Watchdog/watchdog-order-trigger-alert-100.jpg" alt="Order Alert Trigger" width="100" height="113" hspace="8" vspace="8" align="left"></strong>Order Alert Triggers</strong>.</p>
              <p style="color:#3366cc; font-size:9pt; line-height:16pt">Order Alert Triggers are designed to notify you if your store:<br>
                * Has a spike in sales during a period of time<br>
                * Has no sales during a specific period of time<strong><br>
                </strong></p>
              <p style="color:#3366cc; font-size:9pt; line-height:16pt"><strong>You can have the system send an alert...<br>
                * If there are more than 25 orders placed in an hour<br>
                * If there are less than 5 orders placed every five hours<br>
                (You can configure the options on the next screen.)</strong></p>
              <hr width="85%">
              <p style="color:#3366cc; font-size:9pt; line-height:16pt"><img src="http://www.customerparadigm.com/images/Magento/Watchdog/Magento-Error-Warning-Alert-100.jpg" alt="Magento Error" width="100" height="109" hspace="8" vspace="8" align="left"><strong>Magento Errors Trigger.</strong></p>
<p style="color:#3366cc; font-size:9pt; line-height:16pt">You can have the Watchdog system notify you if your store is reporting errors.<br>
  <br>
  </p>
<p style="color:#3366cc; font-size:9pt; line-height:16pt"><strong>For example, you can have the system send an alert:<br>
  * Send an alert every five minutes for Critical Site Errors, and include additional people.<br>
  * Send an alert every two hours for general errors on the Magento site.<br>
  </strong></p>
<p style="color:#3366cc; font-size:9pt; line-height:16pt">The Watchdog system has 4 levels of error detection:</p>
<p style="color:#3366cc; font-size:9pt; line-height:16pt">1. Magento exceptions &amp; reports<br>
  2.  Magento errors and notices, <br>
  3. 
  PHP Errors (Fatal Errors, Warnings, and Notices)<br>
  4. 
  HTTP Status Errors (using external monitoring system)</p>
<hr width="85%"></td>
            </tr>
            <tr>
              <td colspan="2" valign="top"><p style="color:#3366cc; font-size:9pt; line-height:16pt"><span style="font-size:13pt; font-weight:bold;">Watchdog - Add Order Trigger:</span></p>
                <p style="color:#3366cc; font-size:9pt; line-height:16pt"><span style="font-size:13pt; font-weight:bold;"><a href="http://www.customerparadigm.com/images/Magento/Watchdog/Magento-Watchdog-Trigger-Conditions-Screen.gif" target="_blank"><img src="http://www.customerparadigm.com/images/Magento/Watchdog/Magento-Watchdog-Trigger-Conditions-Screen-450.gif" alt="Magento - Order Trigger Alert" width="450" height="229" border="0"></a><br>
                  </span><br>
                <a href="http://www.customerparadigm.com/images/Magento/Watchdog/Magento-Watchdog-Trigger-Conditions-Screen.gif" target="_blank">View larger screenshot &gt;&gt;</a></p>
              <p style="color:#3366cc; font-size:9pt; line-height:16pt"><strong>From this screen, you can create Trigger Alerts that will notify you based on how many orders are placed on your site.</strong></p>
              <p style="color:#3366cc; font-size:9pt; line-height:16pt"><strong>Orders Created: <br>
              </strong>Enter in the number of orders you want to trigger the alert.</p>
              <p style="color:#3366cc; font-size:9pt; line-height:16pt">For example, if you put in 50, the system will look for more than / less than / equal to 50 orders before sending an alert. </p>
              <p style="color:#3366cc; font-size:9pt; line-height:16pt"><strong>Orders(s) create is greater than or less than:</strong><br>
              The system will notify you when orders are:<br>
              * Greater than<br>
              * Greater than or equal to<br>
              * Less Than<br>
              * Less Than or equal to              </p>
              <p style="color:#3366cc; font-size:9pt; line-height:16pt"> ... the number of orders specified above.</p>
              <p style="color:#3366cc; font-size:9pt; line-height:16pt"><strong>Interval:</strong><br>
                Watchdog will alert during specific time intervals:<br>
              * Every Five Minutes<br>
              * Every Half Hour<br>
              * Every Hour<br>
              * Every Two Hours<br>
              * Every Five Hours<br>
              * Every Twelve Hours (Half Day)<br>
              * Every Day (24 hours)<br>
              * Every Week (7 days)</p>
              <p style="color:#3366cc; font-size:9pt; line-height:16pt">For example, you might want a trigger if sales exceed a specific number of orders within a half hour or hour.</p>
              <p style="color:#3366cc; font-size:9pt; line-height:16pt">For simplicity reasons, we have only included these intervals listed above.</p>
              <hr width="85%">
              <p style="color:#3366cc; font-size:9pt; line-height:16pt"><strong><br>
                Alert Me When:</strong><br>
                We've created an easy-to-follow &quot;Alert Me When&quot; description that shows in plain English what the alert will do.<br>
                <br>
                <strong>In our example, the system will Alert You When...</strong><br>
                <strong><br>
                Example #1: Order Spike #1 (&gt;10 orders in five minutes)</strong></p>
              <p style="color:#3366cc; font-size:9pt; line-height:16pt"><img src="http://www.customerparadigm.com/images/Magento/Watchdog/alert-me-when-cropped.gif" width="616" height="44" alt="Alert Me When"></p>
              <p style="color:#3366cc; font-size:9pt; line-height:16pt"><strong>Example #2: Order Spike #2 (&gt;500 orders every hour)</strong></p>
              <p style="color:#3366cc; font-size:9pt; line-height:16pt"><strong><img src="http://www.customerparadigm.com/images/Magento/Watchdog/alert-me-when-example2.gif" width="616" height="44" alt="Alert Me When"></strong></p>
              <p style="color:#3366cc; font-size:9pt; line-height:16pt"><strong>Example #3: No Orders (&lt;2 orders created in five five hours)</strong></p>
              <p style="color:#3366cc; font-size:9pt; line-height:16pt"><strong><img src="http://www.customerparadigm.com/images/Magento/Watchdog/alert-me-when-example3.gif" width="581" height="44" alt="Alert Me No Orders"></strong></p>
              <p style="color:#3366cc; font-size:9pt; line-height:16pt"><strong><strong>Save Button: <br>
              </strong>Make sure to hit the <img src="http://www.customerparadigm.com/images/Magento/Watchdog/save-button.gif" alt="Save" width="104" height="43" align="absmiddle">button so your settings are saved.</strong></p>
              <hr width="85%">
              <p style="color:#3366cc; font-size:9pt; line-height:16pt"><strong><br>
                <br>
              </strong></p></td>
            </tr>
            <tr>
              <td height="1141" colspan="2" valign="top"><p style="color:#3366cc; font-size:9pt; line-height:16pt"><span style="font-size:13pt; font-weight:bold;">Watchdog - Add Error Trigger:</span></p>
                <p style="color:#3366cc; font-size:9pt; line-height:16pt"><span style="font-size:13pt; font-weight:bold;"><a href="http://www.customerparadigm.com/images/Magento/Watchdog/Magento-Watchdog-Create-New-Error-Trigger.gif" target="_blank"><img src="http://www.customerparadigm.com/images/Magento/Watchdog/Magento-Watchdog-Create-New-Error-Trigger-450.gif" alt="Add Error Trigger" width="450" height="257" border="0"></a><br>
                  </span><br>
                <a href="http://www.customerparadigm.com/images/Magento/Watchdog/Magento-Watchdog-Create-New-Error-Trigger.gif" target="_blank">View larger screenshot &gt;&gt;</a></p>
              <p style="color:#3366cc; font-size:9pt; line-height:16pt"><strong>From this screen, you can create an Error Trigger Alerts that will notify you based on when errors occur on your site:</strong></p>
              <p style="color:#3366cc; font-size:9pt; line-height:16pt"><strong>Critical Errors:</strong><br>
                You              can have Watchdog send an alert for only Critical Errors on the site (and perhaps set this to a five minute or half-hour interval). <br>
                <br>
                Critical errors are complete show stoppers (meaning your site is not running, or is about to crash very soon), and mean the user could be seeing a raw PHP error, or cannot checkout or view the site.</p>
              <p style="color:#3366cc; font-size:9pt; line-height:16pt"><strong>General Errors:</strong><br>
                General errors usually give you a little bit more time to fix on the site.  They may not prevent someone from being able to use the site, but depending on your settings for your 
              Magento store, General errors may appear on the front end of the Magento Website.</p>
              <p style="color:#3366cc; font-size:9pt; line-height:16pt"><strong>You may wish to create two separate Trigger Reports for errors. One for critical errors, set for every five minutes; the second might be for general errors, set to every hour, day or week.</strong></p>
              <p style="color:#3366cc; font-size:9pt; line-height:16pt"><strong>Interval:</strong><br>
Watchdog will alert during specific time intervals:<br>
* Every Five Minutes<br>
* Every Half Hour<br>
* Every Hour<br>
* Every Two Hours<br>
* Every Five Hours<br>
* Every Twelve Hours (Half Day)<br>
* Every Day (24 hours)<br>
* Every Week (7 days)</p>
              <p style="color:#3366cc; font-size:9pt; line-height:16pt">For example, you might want a trigger if sales exceed a specific number of orders within a half hour or hour.</p>
              <p style="color:#3366cc; font-size:9pt; line-height:16pt">For simplicity reasons, we have only included these intervals listed above.</p>
              <p style="color:#3366cc; font-size:9pt; line-height:16pt"><strong>Save Button: <br>
            </strong>Make sure to hit the <img src="http://www.customerparadigm.com/images/Magento/Watchdog/save-button.gif" alt="Save" width="104" height="43" align="absmiddle">button so your settings are saved.</p>
              <hr width="85%">
              <p style="color:#3366cc; font-size:9pt; line-height:16pt">&nbsp;</p></td>
            </tr>
            <tr>
              <td colspan="2" valign="top"><p style="color:#3366cc; font-size:9pt; line-height:16pt"><span style="font-size:13pt; font-weight:bold;">Watchdog - Add Error Trigger - Additional Contacts:</span></p>
                <p style="color:#3366cc; font-size:9pt; line-height:16pt"><span style="font-size:13pt; font-weight:bold;"><a href="http://www.customerparadigm.com/images/Magento/Watchdog/Magento-Watchdog-Create-New-Trigger-Email-Contacts.gif" target="_blank"><img src="http://www.customerparadigm.com/images/Magento/Watchdog/Magento-Watchdog-Create-New-Trigger-Email-Contacts-450.gif" alt="Add Error Trigger - Additional Contacts" width="450" height="259" border="0"></a><br>
                  </span><br>
                <a href="http://www.customerparadigm.com/images/Magento/Watchdog/Magento-Watchdog-Create-New-Trigger-Email-Contacts.gif" target="_blank">View larger screenshot &gt;&gt;</a></p>
              <p style="color:#3366cc; font-size:9pt; line-height:16pt"><strong>On the Watchdog Add / Edit Trigger - Contacts Tab, you can add additional contacts who want to receive the Trigger Alert Emails.</strong></p>
              <p style="color:#3366cc; font-size:9pt; line-height:16pt"><strong>By default, ALL Master Contacts will receive every report.</strong></p>
              <p style="color:#3366cc; font-size:9pt; line-height:16pt">To change the Master Contacts, navigate to:<br>
                <em>CustomerParadigm-&gt;Watchdog-&gt;Settings</em></p>
              <p style="color:#3366cc; font-size:9pt; line-height:16pt"><strong>Email Contacts:</strong></p>
              <p style="color:#3366cc; font-size:9pt; line-height:16pt">By default all reports are emailed to the Master Contacts, listed above.</p>
              <p style="color:#3366cc; font-size:9pt; line-height:16pt"> If you would like to have this specific report sent to an additional person, please select from the email contacts below.<br>
                <br>
                To add a new email contact, please visit<br>
  <em>CustomerParadigm-&gt;Watchdog-&gt;Contacts</em></p>
              <p style="color:#3366cc; font-size:9pt; line-height:16pt"><br>
                <strong>Save Button: <br>
              </strong>Make sure to hit the <img src="http://www.customerparadigm.com/images/Magento/Watchdog/save-button.gif" alt="Save" width="104" height="43" align="absmiddle">button so your settings are saved.</p>
              <hr width="85%">
              <p style="color:#3366cc; font-size:9pt; line-height:16pt">&nbsp;</p></td>
            </tr>
            <tr>
              <td colspan="2" valign="top"><p style="color:#3366cc; font-size:9pt; line-height:16pt"><span style="font-size:13pt; font-weight:bold;">Need Help With  Watchdog?<br>
              </span>Customer Paradigm can help you install, customize and configure Watchdog for your Magento store, and is also available to help with Magento Development, Migration, Upgrades, Design and Search Engine Optimization (SEO). <b>Visit <a href="http://www.customerparadigm.com/">www.CustomerParadigm.com</a> or call 303.473.4400</b></p>
                <hr width="85%">
              <p style="color:#3366cc; font-size:9pt; line-height:16pt">&nbsp;</p></td>
            </tr>
            <tr>
              <td colspan="2" valign="top">&nbsp;</td>
            </tr>
            <tr>
              <td colspan="2" align="center" valign="top"><p><span style="color:#3366cc; font-size:9pt; line-height:16pt"><b><a href="http://www.customerparadigm.com" style="text-decoration:none;">Watchdog is Powered by:<br>
                <img src="http://www.CustomerParadigm.com/images/Magento/Watchdog/Customer-Paradigm-Magento-Partner-logo-160.jpg" alt="Customer Paradigm - Magento Experts" width="160" height="50" border="0"></a></b></span></p>
                <p><span style="color:#3366cc; font-size:9pt; line-height:16pt"><b>&nbsp;&nbsp;&nbsp;&nbsp;Need Help with Magento or SEO?               Customer Paradigm can help. <br>
              Visit <a href="http://www.customerparadigm.com/">www.CustomerParadigm.com</a> or call 303.473.4400</b></span></p></td>
          </tr>

        </table>
    </td>
</tr>
</table>
<!-- <img height="1" width="1" src="{{var tracking_pixel_src}}" /> -->
</div>